### ISSUE TITLE
Feature request: Better support for kernel, initrd

### ISSUE THREAD

**Issue by benfogle** [ALSchwalm/transient#126]
Our Yocto-based system produces a rootfs, kernel, and initramfs as separate files. I would like to be able to build an image that combines these three. In addition, we want to be able to mix and match kernels with a custom userspace for testing. Something like the following additions to the Imagefile would be helpful:

* `KERNEL <file>`: Override the kernel used when running this image
* `INITRD <file>`: Override the initramfs used when running this image. It would be very helpful if this could be given multiple times, concatenating the files each time. (That makes for a quick way of overriding files in an initramfs.)
* `ARGS <args...>`: Override (append to?) the kernel command line used when running the image

I know it's already possible to do with with args given directly to qemu, but this would simplify customizing and deriving slightly altered versions.

**Comment by ALSchwalm** [comment]
Hmm, I think there are a few issues here. So currently transient image building just produces qcow files. There is not really a convenient way, to my knowledge, to associate arbitrary other data with them. Are you proposing that the actual kernel/intiramfs would be attached to the image in some way? Or just the name/path of those?

What is the benefit of having these things incorporated in to the image rather than using the existing https://transient.readthedocs.io/en/latest/configuration-file/overview functionality?

**Comment by benfogle** [comment]
Having played with transient more, I think I get how it's supposed to be used a little better. I'll close this, and related issues.
