### ISSUE TITLE
Enable clean shutdown

### ISSUE THREAD

**Issue by willabele** [ALSchwalm/transient#43]
I might be missing how to do this, but I'd like a way to use `-ssh` to run a command and then have the VM shutdown cleanly without ssh returning an error.

I was thinking about changing the default behavior of `-ssh` to ssh back into the machine, `sudo shutdown -h now`, then wait for qemu to exit instead of just terminating. I'd also add a `-no-shutdown` flag since there will likely be instances where this behavior is not desired.

**Comment by dlrobertson** [comment]
I'd really like this. If we implement some form of https://github.com/ALSchwalm/transient/issues/40 we'd have `powerdown`:

```
<- { "event": "POWERDOWN",
     "timestamp": { "seconds": 1267040730, "microseconds": 682951 } }
```
According to the manual:

> Emitted when the virtual machine is powered down through the power control system, such as via ACPI. 

We'd also be able to reset, suspend, wakeup, etc. which would be nice.

> I'd also add a -no-shutdown flag since there will likely be instances where this behavior is not desired.

A `-no-reset` flag would be nice too. It is hard to determine where the user should be using qemu flags vs `transient` flags. Is there a benefit to having this as a transient flag instead of just requiring the user to run `transient <transient args> -- -no-shutdown` or `transient <transient args> -- -no-reset`?

**Comment by willabele** [comment]
`-no-shutdown` seems to be a terrible name choice given that qemu has the same option, but very different behavior than what I'm proposing. Maybe `-force-terminate` for my option? I intended for it to be used when you know ahead of time that the VM won't shutdown cleanly and you want transient to just kill it.

I don't have a strong preference between the QMP approach and the ssh approach. The only reason I proposed ssh is that I don't know how well shutdown signals are handled across OSes and architectures.

**Comment by dlrobertson** [comment]
> Maybe -force-terminate for my option? I intended for it to be used when you know ahead of time that the VM won't shutdown cleanly and you want transient to just kill it.

Awesome, yeah that makes sense.

> The only reason I proposed ssh is that I don't know how well shutdown signals are handled across OSes and architectures.

Makes sense. I've used `system_powerdown` from the qemu `monitor` console quite a bit and it seems to work well, but I haven't tried on a arm VM.

**Comment by ALSchwalm** [comment]
Hmm, I think I'd rather do this with something like `-shutdown-timeout`. This would cause the following behavior:

- When the ssh connection terminates wait for `-shutdown-timeout` seconds
- If QEMU exits during this time, return with the exit code from QEMU (we actually always return the QEMU exit code if it exits as of 181d00e5cf30b0ef05a30f8c57b0dab0ae7f432e)
- Otherwise, return the exit code from SSH

I'm generally opposed to having functionality that SSH's back in to the guest and triggers the shutdown, as I feel this runs counter to the `transient` design around "these are short lived vms used for testing/dev". I think for that use-case a clean shutdown should not be the default, so I would expect the default `-shutdown-timeout` above to be 0 seconds.

**Comment by ALSchwalm** [comment]
Ok, I opened a pull request to address this. For the time being, I'm just doing a clean shutdown via QMP. I'd like to change that back to sending SIGTERM in the future, but we definitely need to avoid corrupting the guest disk.
