### ISSUE TITLE
Setting `ssh-port = 22` in config file results in error

### ISSUE THREAD

**Issue by senofsky** [ALSchwalm/transient#91]
Setting `ssh-port = 22` results in the following error:

```
 » transient run -config test/config-files/comprehensive-config
Finished preparation. Starting virtual machine
qemu-system-x86_64: Could not set up host forwarding rule 'tcp::22-:22'
2020-07-23 09:25:35:ERROR:QEMU Process has died
```

Since `transient` sets the ssh port to 22 by default, manually setting the default in the configuration file should _not_ result in an error.

**Comment by ALSchwalm** [comment]
As we discussed, this is because the ssh-port is the port the client connects to _and the port QEMU binds to_. QEMU cannot bind to a low port as an unprivileged user, so this fails as expected. Also, port 22 is not the default. The default is a random high port.

I'm going to go ahead and close this, as I think it's working as expected (I don't think it's worth the added complexity to try to detect this situation and print a clearer error. That seems like something QEMU should be doing).
